### ISSUE TITLE
Support all Slim options

### ISSUE THREAD

**Issue by beausmith** [matsumos/grunt-slim#9]
Using the below gruntfile config options, I tried to use `sort_attrs` option, but it doesn't seem to work.

```
slim:
  production:
    options:
      pretty: true
      sort_attrs: false # not supported
    files:
      'index.html': 'index.slim'
```

Does `grunt-slim` support all [Slim options](http://rdoc.info/gems/slim/file/README.md#Available_options)?
